name = "DataToolkit"
uuid = "dc83c90b-d41d-4e55-bdb7-0fc919659999"
authors = ["TEC <tec@tecosaur.com> and contributors"]
version = "0.8.0"

[deps]
DataToolkitBase = "e209d0c3-e863-446f-9b45-de6ca9730756"
DataToolkitCommon = "9e6fccbf-6142-406a-aa4c-75c1ae647f53"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
DataToolkitBase = "~0.8"
DataToolkitCommon = "~0.8, 0.7"
PrecompileTools = "1.1.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
